// 在此处添加论文
const publications = [
    {
      paper: "ParallelSFL: A Novel Split Federated Learning Framework Tackling Heterogeneity Issues",
      authors: "Yunming Liao, Yang Xu, Hongli Xu, Zhiwai Yao, Liusheng Huang, Chunming Qiao",
      publisher: "The 30th Annual International Conference On Mobile Computing And Networking (MOBICOM 2024)",
      level: `[MOBICOM'24, CCF A]`,
    },
    {
      paper: "Asynchronous Decentralized Federated Learning for Heterogeneous Devices",
      authors: "Yunming Liao, Yang Xu, Hongli Xu, Min Chen, Lun Wang, Chunming Qiao",
      publisher: "IEEE/ACM Transactions on Networking (ToN), 2024",
      level: `[ToN'24, CCF A]`,
    },
    {
      paper: "MergeSFL: Split Federated Learning with Feature Merging and Batch Size Regulation",
      authors: "Yunming Liao, *Yang Xu, Hongli Xu, Lun Wang, Zhiwai Yao, Chunming Qiao",
      publisher: "The 40th IEEE International Conference on Data Engineering (ICDE 2024)",
      level: `[ICDE'24, CCF A]`,
    },
    {
      paper: "Adaptive Configuration for Heterogeneous Participants in Decentralized Federated Learning",
      authors: "Yunming Liao, *Yang Xu, Hongli Xu, Lun Wang, Chen Qian",
      publisher: "The 42nd IEEE International Conference on Computer Communications (INFOCOM 2023)",
      level: `[INFOCOM'23, CCF A]`,
    },
    {
      paper: "Accelerating Federated Learning with Data and Model Parallelism in Edge Computing",
      authors: "Yunming Liao, *Yang Xu, Hongli Xu, Zhiwei Yao, Lun Wang, Chunming Qiao",
      publisher: "IEEE/ACM Transactions on Networking (ToN), 2023",
      level: `[ToN'23, CCF A]`,
    },
    {
      paper: "Decentralized Federated Learning with Adaptive Configuration for Heterogeneous Participants",
      authors: "Yunming Liao, *Yang Xu, Hongli Xu, Lun Wang, Chen Qian, Chunming Qiao",
      publisher: "IEEE Transactions on Mobile Computing (TMC), 2023",
      level: `[TMC'23, CCF A]`,
    },
    {
      paper: "Overcoming Noisy Labels and Non-IID Data in Edge Federated Learning",
      authors: "Yang Xu, Yunming Liao, Lun Wang, *Hongli Xu, Zhida Jiang, Wuyang Zhang",
      publisher: "IEEE Transactions on Mobile Computing (TMC), 2024",
      level: `[TMC'24, CCF A]`,
    },
    {
      paper: "Adaptive Control of Local Updating and Model Compression for Efficient Federated Learning",
      authors: "Yang Xu, Yunming Liao, *Hongli Xu, Zhenguo Ma, Lun Wang, Jianchun Liu",
      publisher: "IEEE Transactions on Mobile Computing (TMC), 2022",
      level: `[TMC'22, CCF A]`,
    },
    {
      paper: "FedSNN: Training Slimmable Neural Network with Federated Learning in Edge Computing",
      authors: "Yang Xu, Yunming Liao, *Hongli Xu, Zhiyuan Wang, Lun Wang, Jianchun Liu, Chen Qian",
      publisher: "IEEE/ACM Transactions on Networking (ToN), 2024",
      level: `[ToN'24, CCF A]`,
    },
    {
      paper: "Enhancing Semi-Supervised Federated Learning with Progressive Training in Heterogeneous Edge Computing",
      authors: "Jianchun Liu, Jun Liu, *Hongli Xu, Yunming Liao, Zhiwei Yao, Min Chen, Chen Qian",
      publisher: "IEEE Transactions on Mobile Computing (TMC), 2024",
      level: `[TMC'24, CCF A]`,
    },
    {
      paper: "Federated Learning with Experience-Driven Model Migration in Heterogeneous Edge Networks",
      authors: "Jianchun Liu, Shilong Wang, *Hongli Xu, Yang Xu, Yunming Liao, Jinyang Huang, He Huang",
      publisher: "IEEE/ACM Transactions on Networking (ToN), 2024",
      level: `[ToN'24, CCF A]`,
    },
    {
      paper: "Ferrari: A Personalized Federated Learning Framework for Heterogeneous Edge Clients",
      authors: "Zhiwei Yao, *Jianchun Liu, Hongli Xu, Lun Wang, Chen Qian, Yunming Liao",
      publisher: "IEEE Transactions on Mobile Computing (TMC), 2024",
      level: `[TMC'24, CCF A]`,
    },
    {
      paper: "YOGA: Adaptive Layer-wise Model Aggregation for Decentralized Federated Learning",
      authors: "Jun Liu, *Jianchun Liu, *Hongli Xu, Yunming Liao, Zhiyuan Wang, Qianpiao Ma",
      publisher: "IEEE Transactions on Networking (ToN), 2023",
      level: `[ToN'23, CCF A]`,
    },
    {
      paper: "Enhancing Federated Learning with Intelligent Model Migration in Heterogeneous Edge Computing",
      authors: "Jianchun Liu, *Yang Xu, *Hongli Xu, Yunming Liao, Zhiyuan Wang, He Huang",
      publisher: "IEEE International Conference on Data Engineering (ICDE), 2022",
      level: `[ICDE'22, CCF A]`,
    },
    {
      paper: "Decentralized Federated Learning with Data Feature Transmission and Neighbor Selection",
      authors: "Wenxiao Lou, Yang Xu, Hongli Xu, Yunming Liao",
      publisher: "IEEE ICPADS 2023",
      level: `[ICPADS'23, CCF C]`,
    },
    {
      paper: "Federated Semi-Supervised Learning with Local and Global Updating Frequency Optimization",
      authors: "Xin Hang, Yang Xu, Hongli Xu, Yunming Liao, Lun Wang",
      publisher: "IEEE CCGrid 2024 ",
      level: `[CCGrid'24, CCF C]`,
    },
    {
      paper: "Accelerating Hierarchical Federated Learning with Model Splitting in Edge Computing",
      authors: "Xiangnan Wang, Yang Xu, Hongli Xu, Zhipeng Sun, Yunming Liao, *Ji Qi",
      publisher: "IEEE ICPADS 2024 ",
      level: `[ICPADS'24, CCF C]`,
    },
  ];